apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: simple-time-service-staging

resources:
  - ../../base

patches:
  - path: patch-staging.yaml
  - path: patch-ingress-staging.yaml

