# Default values for serviceaccounts
awsAccountId: "017019814021"

awsLoadBalancerController:
  enabled: true
  name: aws-load-balancer-controller
  namespace: kube-system
  roleArn: "arn:aws:iam::017019814021:role/simple-time-service-aws-load-balancer-controller-role"

certManager:
  enabled: true
  name: cert-manager
  namespace: cert-manager
  createNamespace: true
  roleArn: "arn:aws:iam::017019814021:role/simple-time-service-cert-manager-role"

clusterAutoscaler:
  enabled: true
  name: cluster-autoscaler-aws-cluster-autoscaler
  namespace: kube-system
  roleArn: "arn:aws:iam::017019814021:role/simple-time-service-cluster-autoscaler-role"
