apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.container.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.container.name }}
    release: prometheus
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.metricsPort }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: metrics
  selector:
    app: {{ .Values.container.name }}
