apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-time-service-ingress
spec:
  rules:
    - host: <ENV_NAME>-time.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: simple-time-service
                port:
                  number: 80
  tls:
    - hosts:
        - <ENV_NAME>-time.example.com
      secretName: <ENV_NAME>-time-tls


