apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-time-service-ingress
  annotations:
    alb.ingress.kubernetes.io/group.name: trainerkarthik-shop
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
    # Cert-manager annotations for Let's Encrypt
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: alb
  rules:
    - host: time.kart24.shop
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: simple-time-service
                port:
                  number: 80
  tls:
    - hosts:
        - time.kart24.shop
      secretName: simple-time-service-tls


