apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: simple-time-service

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - servicemonitor.yaml
  # Note: ClusterIssuer is cluster-scoped and should be applied separately
  # Apply manually: kubectl apply -f clusterissuer.yaml
  # - clusterissuer.yaml


