{{- if and .Values.ingress.enabled .Values.elasticsearch.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elasticsearch-ingress
  namespace: {{ .Values.ingress.namespace }}
  annotations:
    {{- range $k, $v := .Values.ingress.commonAnnotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
    alb.ingress.kubernetes.io/backend-protocol: {{ .Values.elasticsearch.backendProtocol }}
    alb.ingress.kubernetes.io/healthcheck-protocol: {{ .Values.elasticsearch.healthcheckProtocol }}
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.elasticsearch.healthcheckPath }}
    alb.ingress.kubernetes.io/success-codes: {{ .Values.elasticsearch.successCodes | quote }}

spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.elasticsearch.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.elasticsearch.serviceName }}
                port:
                  number: {{ .Values.elasticsearch.servicePort }}
{{- end }}