{{- if and .Values.ingress.enabled .Values.elasticsearch.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: elasticsearch-ingress
  namespace: {{ .Values.namespace.name }}
  annotations:
    {{- range $key, $value := .Values.ingress.commonAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    
    {{- range $key, $value := .Values.elasticsearch.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.elasticsearch.healthcheckPath | default "/_cluster/health" | quote }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.elasticsearch.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.elasticsearch.serviceName }}
                port:
                  number: {{ .Values.elasticsearch.servicePort }}
{{- end }}
