{{- if and .Values.ingress.enabled .Values.kibana.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana-ingress
  namespace: {{ .Values.namespace.name }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    # Override healthcheck path for Kibana
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.kibana.healthcheckPath | quote }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.kibana.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.kibana.serviceName }}
                port:
                  number: {{ .Values.kibana.servicePort }}
{{- end }}
