ingress:
  enabled: true
  commonAnnotations:
    alb.ingress.kubernetes.io/group.name: kart24-shop
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:017019814021:certificate/ec034773-a62d-4646-bacb-8ce132c68473

elasticsearch:
  namespace: logging
  className: alb
  host: elasticsearch.kart24.shop
  serviceName: elasticsearch-master
  servicePort: 9200
  backendProtocol: HTTPS
  healthcheckProtocol: HTTPS
  healthcheckPath: /_cluster/health?local=true
  successCodes: "200"

kibana:
  namespace: logging
  className: alb
  host: kibana.kart24.shop
  serviceName: kibana-kibana
  servicePort: 5601
  backendProtocol: HTTP
  healthcheckProtocol: HTTP
  healthcheckPath: /
  successCodes: "200,302"