apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default  # Base namespace, resources specify their own

resources:
  - aws-load-balancer-controller-sa.yaml
  - cluster-autoscaler-sa.yaml
  - cert-manager-sa.yaml
  - cert-manager-namespace.yaml

