name: Deploy Prometheus (Prod)

on:
  push:
    branches:
      - fastapi
    paths:
      - 'helmfile/**'
      - '.github/workflows/helmfile.yaml'


jobs:
  helm-deploy-prod:
    runs-on: ubuntu-latest
    environment: prod   # enables manual approval

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.0

      - name: Setup Helmfile
        uses: helmfile/helmfile-action@v1
        with:
          version: v1.3.2

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region us-east-1 \
            --name simple-time-service-prod

      - name: Deploy Prometheus Stack (prod)
        run: |
          #helmfile -f helmfile/helmfile.yaml diff
          helmfile -f helmfile/helmfile-prom-prod.yaml apply