jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.env }}

    env:
      AWS_DEFAULT_REGION: us-east-1
      TF_ROOT: infra/environments/${{ github.event.inputs.env }}
      CONFIRM_TEXT: ${{ github.event.inputs.confirm }}

    steps:
      - name: Stop if not confirmed
        run: |
          if [ "$CONFIRM_TEXT" != "DESTROY" ]; then
            echo "You must type DESTROY exactly. Aborting."
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Terraform Init
        working-directory: ${{ env.TF_ROOT }}
        run: terraform init

      - name: Terraform Destroy
        working-directory: ${{ env.TF_ROOT }}
        run: terraform destroy -auto-approve -var-file=terraform.tfvars
