name: Terraform

on:
  pull_request:
    branches: [main, develop]
    paths:
      - "infra/**"
      - ".github/workflows/terraform.yml"

  push:
    branches: [main, develop]
    paths:
      - "infra/**"
      - ".github/workflows/terraform.yml"

env:
  TF_ROOT: infra/environments/prod
  AWS_DEFAULT_REGION: us-east-1
  PROJECT_NAME: simple-time-service
  ENVIRONMENT: prod

# --------------------
# STAGE 1: TERRAFORM PLAN (on PRs)
# --------------------
jobs:
  plan:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Terraform init
        working-directory: ${{ env.TF_ROOT }}
        run: terraform init

      - name: Terraform validate
        working-directory: ${{ env.TF_ROOT }}
        run: terraform validate

      - name: Terraform plan
        working-directory: ${{ env.TF_ROOT }}
        run: terraform plan

# --------------------
# STAGE 2: TERRAFORM APPLY (on push to main/develop)
# --------------------
  apply:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    needs: plan
    environment: prod
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Terraform init
        working-directory: ${{ env.TF_ROOT }}
        run: terraform init

      - name: Terraform apply
        working-directory: ${{ env.TF_ROOT }}
        run: terraform apply -auto-approve -var-file=terraform.tfvars

